[package]
name = "lindera"
version = "0.1.2"
authors = ["Minoru Osuka <minoru.osuka@gmail.com>"]
edition = "2018"
description = "A Japanese Morphological Analysis Library written in Rust."
homepage = "https://github.com/bayard-search/lindera"
repository = "https://github.com/bayard-search/lindera"
readme = "README.md"
keywords = ["tokenizer", "japanese", "morphological", "analyzer"]
categories = ["text-processing"]
license = "MIT"
exclude = ["dict", "mecab-ipadic/**/*"]

[dependencies]
bincode = "1.2.1"
byteorder = "1.3.2"
encoding = "0.2.33"
lindera-ipadic = "0.1.3"
serde = {version="1.0.104", features = ["derive"] }
serde_json = "1.0.45"
tantivy-fst = "0.2.1"

[dev-dependencies]
criterion = "0.3.1"

[profile.release]
debug = false
lto = true

[[bench]]
name = "bench"
harness = false

